-- Use the isolated annual-kpi location; never replay the inherited migration chain.
ALTER TABLE role ADD COLUMN default_review_frequency VARCHAR(20);
ALTER TABLE role ADD CONSTRAINT chk_role_default_review_frequency
    CHECK (default_review_frequency IN ('MONTHLY', 'QUARTERLY', 'ANNUALLY'));

CREATE TABLE annual_kpi_review_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_number VARCHAR(36) NOT NULL,
    name VARCHAR(255),
    start_date DATE,
    end_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    company_kpi_weight NUMERIC(5,2),
    department_kpi_weight NUMERIC(5,2),
    individual_kpi_weight NUMERIC(5,2),
    kpi_performance_weight NUMERIC(5,2) DEFAULT 50.00,
    attitude_evaluation_weight NUMERIC(5,2) DEFAULT 50.00,
    annual_kpi_consolidation_method VARCHAR(30),
    company_kpi_creation_deadline DATE,
    department_kpi_creation_deadline DATE,
    individual_kpi_submission_deadline DATE,
    individual_kpi_approval_deadline DATE,
    self_assessment_days_after_checkpoint INTEGER,
    superior_assessment_days_after_self_deadline INTEGER,
    attitude_self_assessment_deadline DATE,
    superior_attitude_evaluation_deadline DATE,
    appraisal_recommendation_deadline DATE,
    hr_finalisation_deadline DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES staff(id),
    updated_by UUID REFERENCES staff(id),
    opened_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    CONSTRAINT uq_annual_kpi_period_reference UNIQUE (reference_number),
    CONSTRAINT uq_annual_kpi_period_name UNIQUE (name),
    CONSTRAINT chk_annual_kpi_period_status CHECK (status IN ('DRAFT', 'UPCOMING', 'OPEN', 'CLOSED')),
    CONSTRAINT chk_annual_kpi_period_dates CHECK (start_date < end_date),
    CONSTRAINT chk_annual_kpi_period_name CHECK (name IS NULL OR LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_annual_kpi_period_weights CHECK (
        company_kpi_weight BETWEEN 0 AND 100 AND department_kpi_weight BETWEEN 0 AND 100
        AND individual_kpi_weight BETWEEN 0 AND 100 AND kpi_performance_weight BETWEEN 0 AND 100
        AND attitude_evaluation_weight BETWEEN 0 AND 100),
    CONSTRAINT chk_annual_kpi_period_offsets CHECK (
        self_assessment_days_after_checkpoint > 0 AND superior_assessment_days_after_self_deadline > 0),
    CONSTRAINT chk_annual_kpi_period_consolidation CHECK (
        annual_kpi_consolidation_method IN ('FINAL_CHECKPOINT', 'AVERAGE')),
    CONSTRAINT chk_annual_kpi_period_published_configuration CHECK (status = 'DRAFT' OR (
        name IS NOT NULL AND start_date IS NOT NULL AND end_date IS NOT NULL
        AND company_kpi_weight IS NOT NULL AND department_kpi_weight IS NOT NULL
        AND individual_kpi_weight IS NOT NULL AND kpi_performance_weight IS NOT NULL
        AND attitude_evaluation_weight IS NOT NULL
        AND company_kpi_weight + department_kpi_weight + individual_kpi_weight = 100
        AND kpi_performance_weight + attitude_evaluation_weight = 100
        AND annual_kpi_consolidation_method IS NOT NULL
        AND self_assessment_days_after_checkpoint IS NOT NULL
        AND superior_assessment_days_after_self_deadline IS NOT NULL))
);
CREATE INDEX idx_annual_kpi_period_status_dates ON annual_kpi_review_period(status, start_date, end_date);

CREATE TABLE review_period_role_configuration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_period_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    review_frequency VARCHAR(20) NOT NULL,
    CONSTRAINT fk_review_period_role_period FOREIGN KEY (review_period_id) REFERENCES annual_kpi_review_period(id),
    CONSTRAINT fk_review_period_role_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT uq_review_period_role UNIQUE (review_period_id, role_id),
    CONSTRAINT chk_review_period_role_frequency CHECK (review_frequency IN ('MONTHLY', 'QUARTERLY', 'ANNUALLY'))
);
CREATE INDEX idx_review_period_role_role ON review_period_role_configuration(role_id);

CREATE TABLE review_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_period_id BIGINT NOT NULL,
    review_frequency VARCHAR(20) NOT NULL,
    sequence_number INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    self_assessment_deadline DATE NOT NULL,
    superior_assessment_deadline DATE NOT NULL,
    CONSTRAINT fk_review_checkpoint_period FOREIGN KEY (review_period_id) REFERENCES annual_kpi_review_period(id),
    CONSTRAINT uq_review_checkpoint_sequence UNIQUE (review_period_id, review_frequency, sequence_number),
    CONSTRAINT chk_review_checkpoint_frequency CHECK (review_frequency IN ('MONTHLY', 'QUARTERLY', 'ANNUALLY')),
    CONSTRAINT chk_review_checkpoint_sequence CHECK (sequence_number > 0),
    CONSTRAINT chk_review_checkpoint_dates CHECK (start_date <= end_date),
    CONSTRAINT chk_review_checkpoint_deadlines CHECK (
        end_date < self_assessment_deadline AND self_assessment_deadline < superior_assessment_deadline)
);

CREATE TABLE review_period_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_period_id BIGINT NOT NULL,
    staff_id UUID NOT NULL,
    staff_name VARCHAR(255),
    role_id BIGINT,
    role_name VARCHAR(255),
    department_id BIGINT,
    department_name VARCHAR(255),
    superior_id UUID,
    superior_name VARCHAR(255),
    review_frequency VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_participant_period FOREIGN KEY (review_period_id) REFERENCES annual_kpi_review_period(id),
    CONSTRAINT fk_review_participant_staff FOREIGN KEY (staff_id) REFERENCES staff(id),
    CONSTRAINT fk_review_participant_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT fk_review_participant_department FOREIGN KEY (department_id) REFERENCES org_chart(id),
    CONSTRAINT fk_review_participant_superior FOREIGN KEY (superior_id) REFERENCES staff(id),
    CONSTRAINT uq_review_period_participant UNIQUE (review_period_id, staff_id),
    CONSTRAINT chk_review_participant_frequency CHECK (review_frequency IN ('MONTHLY', 'QUARTERLY', 'ANNUALLY'))
);
CREATE INDEX idx_review_participant_staff ON review_period_participant(staff_id, review_period_id);
CREATE INDEX idx_review_participant_superior ON review_period_participant(review_period_id, superior_id);
CREATE INDEX idx_review_participant_department ON review_period_participant(review_period_id, department_id);
CREATE INDEX idx_review_participant_role ON review_period_participant(role_id);
