-- Do not infer historical Employee Levels from job names or current role assignments.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM review_period_participant)
       OR EXISTS (SELECT 1 FROM review_period_role_configuration c
                  JOIN annual_kpi_review_period p ON p.id=c.review_period_id WHERE p.status<>'DRAFT') THEN
        RAISE EXCEPTION 'V29 requires an explicit reviewed historical Employee Level mapping before migrating published role configurations or participants';
    END IF;
END $$;

CREATE TABLE employee_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    display_order INTEGER NOT NULL UNIQUE,
    default_company_kpi_weight NUMERIC(5,2) NOT NULL,
    default_department_kpi_weight NUMERIC(5,2) NOT NULL,
    default_individual_kpi_weight NUMERIC(5,2) NOT NULL,
    CONSTRAINT chk_employee_level_defaults CHECK (
        default_company_kpi_weight BETWEEN 0 AND 100 AND default_department_kpi_weight BETWEEN 0 AND 100
        AND default_individual_kpi_weight BETWEEN 0 AND 100
        AND default_company_kpi_weight + default_department_kpi_weight + default_individual_kpi_weight = 100)
);
INSERT INTO employee_level(code,name,display_order,default_company_kpi_weight,default_department_kpi_weight,default_individual_kpi_weight)
VALUES ('TOP_MANAGEMENT','Top Management',1,50,30,20),
       ('MIDDLE_MANAGEMENT','Middle Management',2,35,35,30),
       ('JUNIOR_MANAGEMENT','Junior Management',3,25,35,40),
       ('EXECUTIVE','Executive',4,15,25,60),
       ('ADMIN','Admin',5,10,10,80),
       ('GENERAL','General',6,5,5,90);

ALTER TABLE role ADD COLUMN employee_level_id BIGINT;
ALTER TABLE role ADD CONSTRAINT fk_role_employee_level FOREIGN KEY (employee_level_id) REFERENCES employee_level(id);
CREATE INDEX idx_role_employee_level ON role(employee_level_id);

CREATE TABLE review_period_employee_level_configuration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_period_id BIGINT NOT NULL,
    employee_level_id BIGINT NOT NULL,
    CONSTRAINT fk_period_level_period FOREIGN KEY (review_period_id) REFERENCES annual_kpi_review_period(id),
    CONSTRAINT fk_period_level_employee_level FOREIGN KEY (employee_level_id) REFERENCES employee_level(id),
    company_kpi_weight NUMERIC(5,2),
    department_kpi_weight NUMERIC(5,2),
    individual_kpi_weight NUMERIC(5,2),
    CONSTRAINT uq_period_employee_level UNIQUE (review_period_id,employee_level_id),
    CONSTRAINT uq_period_level_config_id UNIQUE (review_period_id,id),
    CONSTRAINT chk_period_level_weight_ranges CHECK (
        company_kpi_weight BETWEEN 0 AND 100 AND department_kpi_weight BETWEEN 0 AND 100
        AND individual_kpi_weight BETWEEN 0 AND 100)
);
CREATE INDEX idx_period_level_employee_level ON review_period_employee_level_configuration(employee_level_id);
-- Preserve original configurations, including incomplete Drafts; do not apply example defaults retrospectively.
INSERT INTO review_period_employee_level_configuration(review_period_id,employee_level_id,company_kpi_weight,department_kpi_weight,individual_kpi_weight)
SELECT p.id,l.id,p.company_kpi_weight,p.department_kpi_weight,p.individual_kpi_weight
FROM annual_kpi_review_period p CROSS JOIN employee_level l;

ALTER TABLE review_period_role_configuration ADD COLUMN employee_level_configuration_id BIGINT;
ALTER TABLE review_period_role_configuration ADD CONSTRAINT fk_period_role_level_config
    FOREIGN KEY (review_period_id,employee_level_configuration_id)
    REFERENCES review_period_employee_level_configuration(review_period_id,id);
CREATE INDEX idx_period_role_level_config ON review_period_role_configuration(review_period_id,employee_level_configuration_id);
ALTER TABLE review_period_participant ADD COLUMN employee_level_configuration_id BIGINT NOT NULL;
ALTER TABLE review_period_participant ADD CONSTRAINT fk_participant_level_config
    FOREIGN KEY (review_period_id,employee_level_configuration_id)
    REFERENCES review_period_employee_level_configuration(review_period_id,id);
CREATE INDEX idx_participant_level_config ON review_period_participant(review_period_id,employee_level_configuration_id);

-- Old global columns remain as migration evidence only, not active configuration.
ALTER TABLE annual_kpi_review_period DROP CONSTRAINT chk_annual_kpi_period_weights;
ALTER TABLE annual_kpi_review_period ADD CONSTRAINT chk_annual_kpi_period_weights CHECK (
    kpi_performance_weight BETWEEN 0 AND 100 AND attitude_evaluation_weight BETWEEN 0 AND 100);
ALTER TABLE annual_kpi_review_period DROP CONSTRAINT chk_annual_kpi_period_published_configuration;
ALTER TABLE annual_kpi_review_period ADD CONSTRAINT chk_annual_kpi_period_published_configuration CHECK (status='DRAFT' OR (
    name IS NOT NULL AND start_date IS NOT NULL AND end_date IS NOT NULL
    AND kpi_performance_weight IS NOT NULL AND attitude_evaluation_weight IS NOT NULL
    AND kpi_performance_weight + attitude_evaluation_weight = 100
    AND annual_kpi_consolidation_method IS NOT NULL
    AND self_assessment_days_after_checkpoint IS NOT NULL AND superior_assessment_days_after_self_deadline IS NOT NULL));
