-- Whole-plan lifecycle; employee applicability is materialised without duplicating definitions.
ALTER TABLE review_period_participant ADD CONSTRAINT uq_participant_id_period UNIQUE (id, review_period_id);
CREATE TABLE kpi_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_period_id BIGINT NOT NULL REFERENCES annual_kpi_review_period(id),
    level VARCHAR(20) NOT NULL,
    department_id BIGINT REFERENCES org_chart(id),
    owner_participant_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL REFERENCES staff(id), updated_by UUID NOT NULL REFERENCES staff(id),
    CONSTRAINT uq_kpi_plan_id_period UNIQUE (id, review_period_id),
    CONSTRAINT fk_kpi_plan_owner_period FOREIGN KEY (owner_participant_id, review_period_id)
        REFERENCES review_period_participant(id, review_period_id),
    CONSTRAINT ck_kpi_plan_scope CHECK (
        (level='COMPANY' AND department_id IS NULL AND owner_participant_id IS NULL) OR
        (level='DEPARTMENT' AND department_id IS NOT NULL AND owner_participant_id IS NULL) OR
        (level='INDIVIDUAL' AND department_id IS NULL AND owner_participant_id IS NOT NULL)),
    CONSTRAINT ck_kpi_plan_status CHECK (
        (level='COMPANY' AND status IN ('DRAFT','PUBLISHED')) OR
        (level IN ('DEPARTMENT','INDIVIDUAL') AND status IN ('DRAFT','PENDING_APPROVAL','RETURNED','APPROVED')))
);
CREATE UNIQUE INDEX uq_company_kpi_plan ON kpi_plan(review_period_id) WHERE level='COMPANY';
CREATE UNIQUE INDEX uq_department_kpi_plan ON kpi_plan(review_period_id,department_id) WHERE level='DEPARTMENT';
CREATE UNIQUE INDEX uq_individual_kpi_plan ON kpi_plan(owner_participant_id) WHERE level='INDIVIDUAL';
CREATE INDEX idx_kpi_plan_period_level_status ON kpi_plan(review_period_id,level,status);
CREATE TABLE kpi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL, review_period_id BIGINT NOT NULL,
    name VARCHAR(255), description TEXT, perspective VARCHAR(255), kra VARCHAR(255),
    target TEXT, measurement_unit VARCHAR(100), weightage NUMERIC(5,2),
    CONSTRAINT uq_kpi_id_period UNIQUE (id,review_period_id),
    CONSTRAINT fk_kpi_plan_period FOREIGN KEY (plan_id,review_period_id) REFERENCES kpi_plan(id,review_period_id),
    CONSTRAINT ck_kpi_weightage CHECK (weightage BETWEEN 0 AND 100)
);
CREATE INDEX idx_kpi_plan ON kpi(plan_id);
CREATE TABLE kpi_scoring_definition (
    kpi_id BIGINT NOT NULL REFERENCES kpi(id) ON DELETE CASCADE,
    point INTEGER NOT NULL CHECK (point BETWEEN 1 AND 5),
    definition TEXT NOT NULL CHECK (length(trim(definition)) > 0),
    PRIMARY KEY (kpi_id,point)
);
CREATE TABLE employee_kpi_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id BIGINT NOT NULL, participant_id BIGINT NOT NULL, review_period_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_employee_kpi_assignment UNIQUE (kpi_id,participant_id),
    CONSTRAINT fk_assignment_kpi_period FOREIGN KEY (kpi_id,review_period_id) REFERENCES kpi(id,review_period_id),
    CONSTRAINT fk_assignment_participant_period FOREIGN KEY (participant_id,review_period_id)
        REFERENCES review_period_participant(id,review_period_id)
);
CREATE INDEX idx_assignment_participant ON employee_kpi_assignment(participant_id);
ALTER TABLE authority DROP CONSTRAINT IF EXISTS authority_name_check;
ALTER TABLE authority ADD CONSTRAINT authority_name_check CHECK (name IN (
    'ROLE_USER','CAN_VIEW_ACCESS_CONTROL','CAN_MANAGE_ACCESS_CONTROL','CAN_VIEW_STAFF','CAN_MANAGE_STAFF',
    'CAN_VIEW_INVISIBLE_ROLE','CAN_MANAGE_ROLE','CAN_MANAGE_COMPETENCY','CAN_PROPOSE_ROLE_COMPETENCIES',
    'CAN_MANAGE_CAREER_PATHWAY','CAN_MANAGE_ORG_CHART','CAN_MANAGE_TRAINING','CAN_ASSIGN_TRAINING',
    'CAN_MANAGE_LEARNING_MATERIAL','CAN_MANAGE_EVALUATION','CAN_MANAGE_EVALUATION_CYCLE',
    'CAN_MANAGE_ANNUAL_KPI_REVIEW_PERIOD','CAN_MANAGE_COMPANY_KPI'));
INSERT INTO authority(name,description_key,label_key) VALUES
    ('CAN_MANAGE_COMPANY_KPI','auth.can.manage.company.kpi.desc','auth.can.manage.company.kpi');
-- MD authority must be explicitly provisioned through the existing RBAC UI.
