-- Case-specific pre-creation consent; existing normal approval history remains unchanged.
DO $$
BEGIN
    IF to_regclass(current_schema() || '.individual_kpi_assistance_authorization') IS NOT NULL THEN
        RAISE EXCEPTION 'Untracked Individual KPI assistance table; reconcile before applying V36';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema()
        AND table_name='kpi_plan' AND column_name='assistance_authorization_id'
        AND (udt_name <> 'int8' OR is_nullable <> 'YES' OR column_default IS NOT NULL)) THEN
        RAISE EXCEPTION 'Incompatible untracked KPI assistance reference';
    END IF;
END $$;
CREATE TABLE individual_kpi_assistance_authorization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_participant_id BIGINT NOT NULL REFERENCES review_period_participant(id),
    superior_id UUID NOT NULL REFERENCES staff(id),
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    requested_at TIMESTAMPTZ NOT NULL,
    authorized_at TIMESTAMPTZ,
    authorized_by UUID REFERENCES staff(id),
    consumed_at TIMESTAMPTZ,
    CONSTRAINT uq_assistance_case UNIQUE(owner_participant_id,superior_id),
    CONSTRAINT uq_assistance_plan_scope UNIQUE(id,owner_participant_id,superior_id),
    CONSTRAINT ck_assistance_state CHECK (
        (status='REQUESTED' AND authorized_at IS NULL AND authorized_by IS NULL AND consumed_at IS NULL) OR
        (status='AUTHORIZED' AND authorized_at IS NOT NULL AND authorized_by IS NOT NULL AND consumed_at IS NULL) OR
        (status='CONSUMED' AND authorized_at IS NOT NULL AND authorized_by IS NOT NULL AND consumed_at IS NOT NULL)),
    CONSTRAINT ck_assistance_dates CHECK (authorized_at >= requested_at AND consumed_at >= authorized_at)
);
CREATE INDEX idx_assistance_hr_queue ON individual_kpi_assistance_authorization(status,requested_at,id);
CREATE INDEX idx_assistance_superior ON individual_kpi_assistance_authorization(superior_id,requested_at,id);
ALTER TABLE kpi_plan ADD COLUMN IF NOT EXISTS assistance_authorization_id BIGINT;
ALTER TABLE kpi_plan ADD CONSTRAINT uq_plan_assistance UNIQUE(assistance_authorization_id);
ALTER TABLE kpi_plan ADD CONSTRAINT fk_plan_assistance_scope
    FOREIGN KEY(assistance_authorization_id,owner_participant_id,created_by)
    REFERENCES individual_kpi_assistance_authorization(id,owner_participant_id,superior_id);
ALTER TABLE kpi_plan ADD CONSTRAINT ck_assisted_kpi_plan CHECK
    (assistance_authorization_id IS NULL OR
        (level='INDIVIDUAL' AND status IN ('DRAFT','APPROVED') AND submitted_at IS NULL
         AND submitted_by IS NULL AND submitted_to_superior_id IS NULL AND submitted_late IS NULL));
-- Assisted confirmation is direct, not a fabricated employee submission/second approval.
ALTER TABLE kpi_plan DROP CONSTRAINT ck_individual_submission_metadata;
ALTER TABLE kpi_plan ADD CONSTRAINT ck_individual_submission_metadata CHECK
    (level <> 'INDIVIDUAL' OR status='DRAFT' OR assistance_authorization_id IS NOT NULL OR
        (submitted_at IS NOT NULL AND submitted_by IS NOT NULL AND submitted_late IS NOT NULL
         AND submitted_to_superior_id IS NOT NULL));
ALTER TABLE authority DROP CONSTRAINT authority_name_check;
ALTER TABLE authority ADD CONSTRAINT authority_name_check CHECK (name IN (
    'ROLE_USER','CAN_VIEW_ACCESS_CONTROL','CAN_MANAGE_ACCESS_CONTROL','CAN_VIEW_STAFF','CAN_MANAGE_STAFF',
    'CAN_VIEW_INVISIBLE_ROLE','CAN_MANAGE_ROLE','CAN_MANAGE_COMPETENCY','CAN_PROPOSE_ROLE_COMPETENCIES',
    'CAN_MANAGE_CAREER_PATHWAY','CAN_MANAGE_ORG_CHART','CAN_MANAGE_TRAINING','CAN_ASSIGN_TRAINING',
    'CAN_MANAGE_LEARNING_MATERIAL','CAN_MANAGE_EVALUATION','CAN_MANAGE_EVALUATION_CYCLE',
    'CAN_MANAGE_ANNUAL_KPI_REVIEW_PERIOD','CAN_MANAGE_COMPANY_KPI','CAN_MANAGE_DEPARTMENT_KPI',
    'CAN_APPROVE_DEPARTMENT_KPI','CAN_REVIEW_INDIVIDUAL_KPI','CAN_AUTHORIZE_INDIVIDUAL_KPI_ASSISTANCE'));
INSERT INTO authority(name,description_key,label_key) VALUES
    ('CAN_AUTHORIZE_INDIVIDUAL_KPI_ASSISTANCE','auth.can.authorize.individual.kpi.assistance.desc',
     'auth.can.authorize.individual.kpi.assistance');
-- Explicitly grant to verified HR Roles through existing RBAC. No automatic Role grants.
