-- Assessment ownership and checkpoint frequency are enforced without duplicating KPI definitions.
ALTER TABLE review_period_participant ADD CONSTRAINT uq_participant_frequency
    UNIQUE (id, review_period_id, review_frequency);
ALTER TABLE review_checkpoint ADD CONSTRAINT uq_checkpoint_frequency
    UNIQUE (id, review_period_id, review_frequency);
ALTER TABLE employee_kpi_assignment ADD CONSTRAINT uq_assignment_owner_period
    UNIQUE (id, participant_id, review_period_id);

CREATE TABLE kpi_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    checkpoint_id BIGINT NOT NULL,
    review_period_id BIGINT NOT NULL,
    review_frequency VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL REFERENCES staff(id), updated_by UUID NOT NULL REFERENCES staff(id),
    submitted_at TIMESTAMPTZ, submitted_by UUID REFERENCES staff(id),
    submitted_to_superior_id UUID REFERENCES staff(id), submitted_late BOOLEAN,
    reviewed_at TIMESTAMPTZ, reviewed_by UUID REFERENCES staff(id), reviewed_late BOOLEAN,
    checkpoint_score NUMERIC(7,4),
    CONSTRAINT uq_assessment_checkpoint UNIQUE (participant_id, checkpoint_id),
    CONSTRAINT uq_assessment_owner_period UNIQUE (id, participant_id, review_period_id),
    CONSTRAINT fk_assessment_participant FOREIGN KEY (participant_id, review_period_id, review_frequency)
        REFERENCES review_period_participant(id, review_period_id, review_frequency),
    CONSTRAINT fk_assessment_checkpoint FOREIGN KEY (checkpoint_id, review_period_id, review_frequency)
        REFERENCES review_checkpoint(id, review_period_id, review_frequency),
    CONSTRAINT ck_assessment_status CHECK (status IN ('DRAFT','PENDING_REVIEW','REVIEWED')),
    CONSTRAINT ck_assessment_submission CHECK (
        (status='DRAFT' AND submitted_at IS NULL AND submitted_by IS NULL
          AND submitted_to_superior_id IS NULL AND submitted_late IS NULL) OR
        (status IN ('PENDING_REVIEW','REVIEWED') AND submitted_at IS NOT NULL AND submitted_by IS NOT NULL
          AND submitted_to_superior_id IS NOT NULL AND submitted_late IS NOT NULL)),
    CONSTRAINT ck_assessment_review CHECK (
        (status <> 'REVIEWED' AND reviewed_at IS NULL AND reviewed_by IS NULL AND reviewed_late IS NULL AND checkpoint_score IS NULL) OR
        (status='REVIEWED' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND reviewed_late IS NOT NULL
          AND checkpoint_score BETWEEN 0 AND 100 AND checkpoint_score IS NOT NULL))
);
CREATE INDEX idx_assessment_route ON kpi_assessment(submitted_to_superior_id,status,submitted_at);
CREATE INDEX idx_assessment_period_status ON kpi_assessment(review_period_id,status);

CREATE TABLE kpi_assessment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL, assignment_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL, review_period_id BIGINT NOT NULL,
    self_point INTEGER CHECK (self_point BETWEEN 1 AND 5), self_comment TEXT,
    superior_point INTEGER CHECK (superior_point BETWEEN 1 AND 5), superior_comment TEXT,
    CONSTRAINT uq_assessment_assignment UNIQUE (assessment_id,assignment_id),
    CONSTRAINT fk_assessment_item_parent FOREIGN KEY (assessment_id,participant_id,review_period_id)
        REFERENCES kpi_assessment(id,participant_id,review_period_id),
    CONSTRAINT fk_assessment_item_assignment FOREIGN KEY (assignment_id,participant_id,review_period_id)
        REFERENCES employee_kpi_assignment(id,participant_id,review_period_id),
    CONSTRAINT ck_assessment_comments CHECK (
        (self_comment IS NULL OR length(self_comment)<=10000) AND
        (superior_comment IS NULL OR length(superior_comment)<=10000))
);
CREATE TABLE kpi_assessment_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES kpi_assessment_item(id),
    storage_key VARCHAR(100) NOT NULL UNIQUE,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL CHECK (content_type IN ('application/pdf','image/png','image/jpeg')),
    size_bytes BIGINT NOT NULL CHECK (size_bytes>0),
    uploaded_by UUID NOT NULL REFERENCES staff(id), uploaded_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_assessment_evidence_item ON kpi_assessment_evidence(item_id);
ALTER TABLE authority DROP CONSTRAINT IF EXISTS authority_name_check;
ALTER TABLE authority ADD CONSTRAINT authority_name_check CHECK (name IN (
    'ROLE_USER','CAN_VIEW_ACCESS_CONTROL','CAN_MANAGE_ACCESS_CONTROL','CAN_VIEW_STAFF','CAN_MANAGE_STAFF',
    'CAN_VIEW_INVISIBLE_ROLE','CAN_MANAGE_ROLE','CAN_MANAGE_COMPETENCY','CAN_PROPOSE_ROLE_COMPETENCIES',
    'CAN_MANAGE_CAREER_PATHWAY','CAN_MANAGE_ORG_CHART','CAN_MANAGE_TRAINING','CAN_ASSIGN_TRAINING',
    'CAN_MANAGE_LEARNING_MATERIAL','CAN_MANAGE_EVALUATION','CAN_MANAGE_EVALUATION_CYCLE',
    'CAN_MANAGE_ANNUAL_KPI_REVIEW_PERIOD','CAN_MANAGE_COMPANY_KPI','CAN_MANAGE_DEPARTMENT_KPI',
    'CAN_APPROVE_DEPARTMENT_KPI','CAN_REVIEW_INDIVIDUAL_KPI','CAN_AUTHORIZE_INDIVIDUAL_KPI_ASSISTANCE',
    'CAN_REVIEW_KPI_ASSESSMENT'));
INSERT INTO authority(name,description_key,label_key) VALUES
    ('CAN_REVIEW_KPI_ASSESSMENT','auth.can.review.kpi.assessment.desc','auth.can.review.kpi.assessment');
-- No role grants or participant backfills: authority is explicitly assigned using existing RBAC.
