-- Reuse the immutable period binding and criteria; never copy the latest global configuration.
ALTER TABLE annual_kpi_review_period ADD CONSTRAINT uq_period_attitude_configuration
    UNIQUE (id, attitude_configuration_id);
ALTER TABLE attitude_criterion ADD CONSTRAINT uq_attitude_criterion_configuration
    UNIQUE (id, configuration_id);

CREATE TABLE attitude_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    review_period_id BIGINT NOT NULL,
    configuration_id BIGINT NOT NULL REFERENCES attitude_configuration(id),
    evaluation_format VARCHAR(20) NOT NULL CHECK (evaluation_format IN ('MANAGER','SALES','OTHERS')),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PENDING_REVIEW','REVIEWED')),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL REFERENCES staff(id), updated_by UUID NOT NULL REFERENCES staff(id),
    submitted_at TIMESTAMPTZ, submitted_by UUID REFERENCES staff(id),
    submitted_to_superior_id UUID REFERENCES staff(id), submitted_late BOOLEAN,
    reviewed_at TIMESTAMPTZ, reviewed_by UUID REFERENCES staff(id), reviewed_late BOOLEAN,
    attitude_score NUMERIC(7,4),
    CONSTRAINT uq_attitude_assessment_participant UNIQUE (participant_id),
    CONSTRAINT uq_attitude_assessment_configuration UNIQUE (id, configuration_id),
    CONSTRAINT fk_attitude_assessment_participant FOREIGN KEY (participant_id,review_period_id)
        REFERENCES review_period_participant(id,review_period_id),
    CONSTRAINT fk_attitude_assessment_binding FOREIGN KEY (review_period_id,configuration_id)
        REFERENCES annual_kpi_review_period(id,attitude_configuration_id),
    CONSTRAINT ck_attitude_assessment_submission CHECK (
        (status='DRAFT' AND submitted_at IS NULL AND submitted_by IS NULL
            AND submitted_to_superior_id IS NULL AND submitted_late IS NULL) OR
        (status IN ('PENDING_REVIEW','REVIEWED') AND submitted_at IS NOT NULL AND submitted_by IS NOT NULL
            AND submitted_to_superior_id IS NOT NULL AND submitted_late IS NOT NULL)),
    CONSTRAINT ck_attitude_assessment_review CHECK (
        (status<>'REVIEWED' AND reviewed_at IS NULL AND reviewed_by IS NULL AND reviewed_late IS NULL AND attitude_score IS NULL) OR
        (status='REVIEWED' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND reviewed_late IS NOT NULL
            AND attitude_score IS NOT NULL AND attitude_score BETWEEN 0 AND 100))
);
CREATE INDEX idx_attitude_assessment_route ON attitude_assessment(submitted_to_superior_id,status,submitted_at);
CREATE INDEX idx_attitude_assessment_period ON attitude_assessment(review_period_id,status);

CREATE TABLE attitude_assessment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL, criterion_id BIGINT NOT NULL, configuration_id BIGINT NOT NULL,
    self_point INTEGER CHECK (self_point BETWEEN 1 AND 5), self_comment TEXT,
    superior_point INTEGER CHECK (superior_point BETWEEN 1 AND 5), superior_comment TEXT,
    CONSTRAINT uq_attitude_assessment_criterion UNIQUE (assessment_id,criterion_id),
    CONSTRAINT fk_attitude_item_parent FOREIGN KEY (assessment_id,configuration_id)
        REFERENCES attitude_assessment(id,configuration_id),
    CONSTRAINT fk_attitude_item_criterion FOREIGN KEY (criterion_id,configuration_id)
        REFERENCES attitude_criterion(id,configuration_id),
    CONSTRAINT ck_attitude_assessment_comments CHECK (
        (self_comment IS NULL OR length(self_comment)<=10000) AND
        (superior_comment IS NULL OR length(superior_comment)<=10000))
);
CREATE INDEX idx_attitude_assessment_item_criterion ON attitude_assessment_item(criterion_id);
-- No configuration/participant backfills or Role grants; UC-11 actions are a separate slice.
