package com.tbm.careerpathlearning.service.impl;

import io.github.cdimascio.dotenv.Dotenv;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.core.io.ClassPathResource;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

@EnabledIfEnvironmentVariable(named="APEX_PHASE3_POSTGRES_TEST",matches="true")
class KpiAssessmentMigrationPostgresTest {
    @Test void forwardMigrationPreservesRowsAndEnforcesOwnershipAndLifecycle() throws Exception {
        var env=Dotenv.configure().directory(".").load();
        var url=env.get("DB_URL");
        assertTrue(List.of("localhost","127.0.0.1","::1").contains(URI.create(url.substring(5)).getHost()));
        try(var c=DriverManager.getConnection(url,env.get("DB_USER"),env.get("DB_PASS"))) {
            c.setAutoCommit(false);
            try {
                var schema="assessment_migration_"+UUID.randomUUID().toString().replace("-","");
                sql(c,"CREATE SCHEMA "+schema);sql(c,"SET LOCAL search_path TO "+schema);
                sql(c,"CREATE TABLE staff(id uuid PRIMARY KEY)");
                sql(c,"INSERT INTO staff VALUES ('00000000-0000-0000-0000-000000000001')");
                sql(c,"CREATE TABLE authority(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100) UNIQUE, description_key text, label_key text)");
                sql(c,"INSERT INTO authority(name) VALUES('ROLE_USER')");
                sql(c,"CREATE TABLE review_period_participant(id bigint PRIMARY KEY,review_period_id bigint,review_frequency varchar(20))");
                sql(c,"CREATE TABLE review_checkpoint(id bigint PRIMARY KEY,review_period_id bigint,review_frequency varchar(20))");
                sql(c,"CREATE TABLE employee_kpi_assignment(id bigint PRIMARY KEY,participant_id bigint,review_period_id bigint)");
                sql(c,"INSERT INTO review_period_participant VALUES(1,1,'MONTHLY'),(2,1,'MONTHLY'),(3,2,'MONTHLY')");
                sql(c,"INSERT INTO review_checkpoint VALUES(1,1,'MONTHLY'),(2,1,'QUARTERLY'),(3,2,'MONTHLY')");
                sql(c,"INSERT INTO employee_kpi_assignment VALUES(1,1,1),(2,2,1),(3,3,2)");
                sql(c,new ClassPathResource("db/migration/annual-kpi/V39__kpi_self_assessment.sql").getContentAsString(StandardCharsets.UTF_8));
                assertEquals(3,count(c,"review_period_participant"));assertEquals(3,count(c,"employee_kpi_assignment"));
                assertEquals(2,count(c,"authority"));assertEquals(0,count(c,"kpi_assessment"));
                String insert="INSERT INTO kpi_assessment(id,participant_id,checkpoint_id,review_period_id,review_frequency,created_at,updated_at,created_by,updated_by) VALUES";
                String metadata=",now(),now(),'00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001')";
                sql(c,insert+"(1,1,1,1,'MONTHLY'"+metadata);
                reject(c,"23505",insert+"(2,1,1,1,'MONTHLY'"+metadata);
                reject(c,"23503",insert+"(2,1,2,1,'MONTHLY'"+metadata);
                reject(c,"23503",insert+"(2,1,3,1,'MONTHLY'"+metadata);
                sql(c,"INSERT INTO kpi_assessment_item(id,assessment_id,assignment_id,participant_id,review_period_id,self_point) VALUES(1,1,1,1,1,5)");
                reject(c,"23503","INSERT INTO kpi_assessment_item(id,assessment_id,assignment_id,participant_id,review_period_id) VALUES(2,1,2,1,1)");
                reject(c,"23503","INSERT INTO kpi_assessment_item(id,assessment_id,assignment_id,participant_id,review_period_id) VALUES(2,1,3,3,2)");
                reject(c,"23514","UPDATE kpi_assessment_item SET self_point=0");
                reject(c,"23514","UPDATE kpi_assessment_item SET self_point=6");
                reject(c,"23514","UPDATE kpi_assessment SET status='PENDING_REVIEW'");
                reject(c,"23514","UPDATE kpi_assessment SET checkpoint_score=100");
                reject(c,"23514","INSERT INTO kpi_assessment_evidence(item_id,storage_key,original_filename,content_type,size_bytes,uploaded_by,uploaded_at) VALUES(1,'key','bad.svg','image/svg+xml',5,'00000000-0000-0000-0000-000000000001',now())");
                sql(c,"UPDATE kpi_assessment SET status='PENDING_REVIEW',submitted_at=now(),"
                        +"submitted_by='00000000-0000-0000-0000-000000000001',"
                        +"submitted_to_superior_id='00000000-0000-0000-0000-000000000001',submitted_late=false");
                sql(c,"UPDATE kpi_assessment_item SET superior_point=4,superior_comment='Evidence checked'");
                reject(c,"23514","UPDATE kpi_assessment_item SET superior_point=0");
                reject(c,"23514","UPDATE kpi_assessment_item SET superior_point=6");
                reject(c,"23514","UPDATE kpi_assessment SET status='REVIEWED'");
                sql(c,"UPDATE kpi_assessment SET status='REVIEWED',reviewed_at=now(),"
                        +"reviewed_by='00000000-0000-0000-0000-000000000001',reviewed_late=false,checkpoint_score=80.0000");
                reject(c,"23514","UPDATE kpi_assessment SET checkpoint_score=100.0001");
                reject(c,"23514","UPDATE kpi_assessment SET checkpoint_score=NULL");
                reject(c,"23514","UPDATE kpi_assessment SET reviewed_by=NULL");
                assertEquals(1,count(c,"kpi_assessment"));assertEquals(1,count(c,"kpi_assessment_item"));
            } finally {c.rollback();}
        }
    }
    static void sql(Connection c,String sql) throws SQLException {try(var s=c.createStatement()){s.execute(sql);}}
    static long count(Connection c,String table) throws SQLException {try(var s=c.createStatement();var r=s.executeQuery("SELECT count(*) FROM "+table)){r.next();return r.getLong(1);}}
    static void reject(Connection c,String state,String sql) throws SQLException {
        var savepoint=c.setSavepoint();var failure=assertThrows(SQLException.class,()->sql(c,sql));
        assertEquals(state,failure.getSQLState());c.rollback(savepoint);
    }
}
