package com.tbm.careerpathlearning.service;
import com.tbm.careerpathlearning.dto.*;
import java.util.*;
public interface KpiPlanService {
    List<KpiPeriodContextDto> companyPeriods();
    List<KpiPlanDto> companyPlans();
    KpiPlanDto companyPlan(Long id);
    KpiPlanDto createCompany(KpiPlanRequest request,UUID actor);
    KpiPlanDto updateCompany(Long id,KpiPlanRequest request,UUID actor);
    KpiPlanDto publishCompany(Long id,UUID actor);
    List<KpiPeriodContextDto> departmentPeriods(UUID actor);
    List<KpiDepartmentOptionDto> departmentOptions(UUID actor);
    List<KpiPlanDto> departmentPlans(UUID actor);
    List<KpiPlanDto> pendingDepartmentPlans(UUID actor);
    KpiPlanDto departmentPlan(Long id,UUID actor);
    KpiPlanDto createDepartment(KpiPlanRequest request,UUID actor);
    KpiPlanDto updateDepartment(Long id,KpiPlanRequest request,UUID actor);
    KpiPlanDto submitDepartment(Long id,UUID actor);
    KpiPlanDto approveDepartment(Long id,UUID actor);
    KpiPlanDto returnDepartment(Long id,KpiPlanReturnRequest request,UUID actor);
    List<KpiPeriodContextDto> individualPeriods(UUID actor);
    List<KpiPlanDto> myIndividualPlans(UUID actor);
    List<KpiPlanDto> myAssignedPlans(Long reviewPeriodId,UUID actor);
    List<KpiPlanDto> pendingIndividualPlans(UUID superior);
    List<KpiPlanDto> individualReviewPlans(UUID superior);
    KpiPlanDto individualPlan(Long id,UUID actor);
    KpiPlanDto createIndividual(KpiPlanRequest request,UUID actor);
    KpiPlanDto updateIndividual(Long id,KpiPlanRequest request,UUID actor);
    KpiPlanDto submitIndividual(Long id,UUID actor);
    KpiPlanDto approveIndividual(Long id,UUID superior);
    KpiPlanDto returnIndividual(Long id,KpiPlanReturnRequest request,UUID superior);
    List<KpiAssistanceEmployeeDto> assistanceEmployees(UUID superior);
    List<KpiAssistanceDto> assistanceCases(UUID actor);
    KpiAssistanceDto assistanceCase(Long id,UUID actor);
    KpiAssistanceDto requestAssistance(KpiAssistanceRequest request,UUID superior);
    KpiAssistanceDto authorizeAssistance(Long id,UUID hr);
    KpiPlanDto assistedIndividualPlan(Long authorizationId,UUID superior);
    KpiPlanDto createAssistedIndividual(Long authorizationId,AssistedIndividualKpiPlanRequest request,UUID superior);
    KpiPlanDto updateAssistedIndividual(Long authorizationId,AssistedIndividualKpiPlanRequest request,UUID superior);
    KpiPlanDto confirmAssistedIndividual(Long authorizationId,UUID superior);
}
